name: antarctic_ars_dataset
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - ipywidgets
  - pip
  - mystmd
  - numpy
  - pandas
  - matplotlib
  - xarray
  - netcdf4
  - h5py
  - pytables
  - pip:
    - ray
    - earthaccess
    - tqdm
    - jupyterlab_myst
    - gh-scoped-creds